apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: rinawarp
type: Opaque
stringData:
  JWT_SECRET: M66UwIps8vJAl7PkrmG16ccU5YsVvVSmYX7CJLJJOuO15t1d2iCWEaNrgJ9LzTHB
  SESSION_SECRET: cSvW3DgLwo48RLd8swDb68t2NgtshUITX8XXCokHQyHAoZfNdzRGPaFdR5VJlfDG
  STRIPE_SECRET_KEY: "PLACEHOLDER"
  STRIPE_WEBHOOK_SECRET: "PLACEHOLDER"
  AI_API_KEY: "PLACEHOLDER"
  SENTRY_DSN: "PLACEHOLDER"
  SLACK_WEBHOOK_URL: "PLACEHOLDER"
