apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: rinawarp
type: Opaque
stringData:
  database: rinawarp
  username: rinawarp_admin
  password: O-3gk;ye(q0&z&40;7_1k_Fya!hmGQZJ
