groups:
  - name: node_alerts
    rules:
      - alert: HighCPUUsage
        expr: rate(node_cpu_seconds_total{mode="system"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage detected
          description: CPU usage is above 80% for 5 minutes

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
          description: Memory usage is above 90% for 5 minutes

      - alert: DiskSpaceRunningOut
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Disk space running low
          description: Disk usage is above 85%

  - name: application_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High HTTP error rate
          description: Error rate is above 5% for 5 minutes

      - alert: APILatencyHigh
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High API latency
          description: API latency is above 1 second for 5 minutes

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Service is down
          description: Service {{ $labels.job }} is down

  - name: database_alerts
    rules:
      - alert: PostgresqlDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: PostgreSQL instance is down
          description: PostgreSQL instance has been down for more than 1 minute

      - alert: PostgresqlHighConnections
        expr: sum by (datname) (pg_stat_activity_count) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High number of PostgreSQL connections
          description: More than 80 active connections for 5 minutes

      - alert: PostgresqlSlowQueries
        expr: rate(pg_stat_activity_max_tx_duration{datname!=""}[1m]) > 60
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Slow PostgreSQL queries detected
          description: Queries taking more than 60 seconds detected

  - name: redis_alerts
    rules:
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Redis instance is down
          description: Redis instance has been down for more than 1 minute

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Redis memory usage is high
          description: Redis memory usage is above 80%

  - name: security_alerts
    rules:
      - alert: HighRateLimit
        expr: rate(rate_limit_exceeded_total[5m]) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High rate of rate limit exceeded
          description: Rate limit exceeded more than 100 times in 5 minutes

      - alert: HighAuthFailure
        expr: rate(auth_failures_total[5m]) > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High rate of authentication failures
          description: More than 50 authentication failures in 5 minutes
