[build]
builder = "NIXPACKS"
buildCommand = "cp -R ../.. /workspaces/project && cd /workspaces/project && npm install && npm run build"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 5
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
