name: staging
on:
  push:
    branches:
      - develop
      - feature/*
      - hotfix/*

environment:
  name: staging
  url: https://staging.rinawarptech.com

variables:
  AWS_REGION: us-west-2
  NODE_ENV: staging
  API_URL: https://api.staging.rinawarptech.com
  S3_BUCKET: downloads.staging.rinawarptech.com

branch_protection_rules:
  develop:
    required_status_checks:
      - test
      - build
    required_pull_request_reviews: 1
    enforce_admins: false
