apiVersion: v1
kind: Namespace
metadata:
  name: rinawarp-staging

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: rinawarp-staging
data:
  NODE_ENV: "staging"
  PORT: "3000"
  HOST: "0.0.0.0"
  API_URL: "https://staging-api.rinawarptech.com"
  WEBSITE_URL: "https://staging.rinawarptech.com"
  METRICS_INTERVAL: "60000"
  METRICS_RETENTION: "86400"
  LOG_LEVEL: "debug"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
  namespace: rinawarp-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
      - name: platform
        image: ${GHCR_IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: platform-config
        - secretRef:
            name: platform-secrets
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: platform
  namespace: rinawarp-staging
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: platform

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  namespace: rinawarp-staging
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - staging-api.rinawarptech.com
    secretName: platform-tls-staging
  rules:
  - host: staging-api.rinawarptech.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: platform
            port:
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: platform-hpa
  namespace: rinawarp-staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: platform
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-monitor
  namespace: rinawarp-staging
spec:
  selector:
    matchLabels:
      app: platform
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
