apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: rinawarp-staging
data:
  NODE_ENV: "staging"
  PORT: "3000"
  HOST: "0.0.0.0"
  API_URL: "https://staging-api.rinawarptech.com"
  WEBSITE_URL: "https://staging.rinawarptech.com"
  METRICS_INTERVAL: "60000"
  METRICS_RETENTION: "86400"
  LOG_LEVEL: "debug"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgresql"
  POSTGRES_PORT: "5432"
