apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: platform
  namespaceSelector:
    matchNames:
      - rinawarp-staging
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: postgresql
  namespaceSelector:
    matchNames:
      - rinawarp-staging
  endpoints:
    - port: metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: redis
  namespaceSelector:
    matchNames:
      - rinawarp-staging
  endpoints:
    - port: metrics
      interval: 30s
