# Task Definitions
# Schedule format: * * * * * (minute hour day month weekday)

tasks:
  # Daily Tasks
  - name: security-scan
    type: security
    schedule: "0 5 * * *"  # Daily at 05:00
    command: "./scripts/security-scan.sh"
    notify: true
    environment:
      SCAN_LEVEL: full
      REPORT_PATH: /var/log/security-scans

  - name: documentation-check
    type: documentation
    schedule: "0 7 * * *"  # Daily at 07:00
    command: "./scripts/doc-monitor.js"
    notify: true

  - name: usage-analysis
    type: analytics
    schedule: "0 8 * * *"  # Daily at 08:00
    command: "./scripts/analyze-usage.js"
    notify: false

  - name: status-page-update
    type: monitoring
    schedule: "0 * * * *"  # Every hour
    command: "./scripts/generate-status-page.js"
    notify: false

  - name: error-monitoring
    type: monitoring
    schedule: "*/5 * * * *"  # Every 5 minutes
    command: "./scripts/error-monitor.js"
    notify: true
    environment:
      ALERT_THRESHOLD: high

  # Weekly Tasks
  - name: full-test-suite
    type: testing
    schedule: "0 6 * * 0"  # Sunday at 06:00
    command: "./scripts/test-monitor.js"
    notify: true
    environment:
      TEST_ENV: ci
      COVERAGE_THRESHOLD: 80

  - name: report-aggregation
    type: reporting
    schedule: "0 0 * * 1"  # Monday at 00:00
    command: "./scripts/aggregate-reports.js"
    notify: true

  - name: log-rotation
    type: maintenance
    schedule: "0 4 * * 0"  # Sunday at 04:00
    command: "./scripts/rotate-logs.sh"
    notify: false
    environment:
      RETENTION_DAYS: 30

  # Monthly Tasks
  - name: security-audit
    type: security
    schedule: "0 1 1 * *"  # 1st of month at 01:00
    command: "./scripts/security-audit.sh"
    notify: true
    environment:
      AUDIT_LEVEL: comprehensive
      SCAN_DEPENDENCIES: true

  - name: performance-review
    type: performance
    schedule: "0 2 1 * *"  # 1st of month at 02:00
    command: "./scripts/performance-review.js"
    notify: true
    environment:
      ANALYSIS_PERIOD: 30d

  - name: dependency-updates
    type: maintenance
    schedule: "0 3 1 * *"  # 1st of month at 03:00
    command: "./scripts/update-dependencies.sh"
    notify: true
    environment:
      UPDATE_LEVEL: minor
      AUTO_MERGE: false

  - name: documentation-review
    type: documentation
    schedule: "0 4 1 * *"  # 1st of month at 04:00
    command: "./scripts/doc-review.js"
    notify: true

  # Quarterly Tasks
  - name: architecture-review
    type: architecture
    schedule: "0 1 1 */3 *"  # 1st day of every 3rd month at 01:00
    command: "./scripts/architecture-review.js"
    notify: true
    environment:
      REVIEW_DEPTH: comprehensive

  - name: capacity-planning
    type: infrastructure
    schedule: "0 2 1 */3 *"  # 1st day of every 3rd month at 02:00
    command: "./scripts/capacity-planning.js"
    notify: true
    environment:
      FORECAST_MONTHS: 6

  - name: penetration-testing
    type: security
    schedule: "0 3 1 */3 *"  # 1st day of every 3rd month at 03:00
    command: "./scripts/pentest.sh"
    notify: true
    environment:
      TEST_SCOPE: full
      REPORT_FORMAT: detailed

  - name: documentation-overhaul
    type: documentation
    schedule: "0 4 1 */3 *"  # 1st day of every 3rd month at 04:00
    command: "./scripts/doc-overhaul.js"
    notify: true
    environment:
      UPDATE_DIAGRAMS: true
      VALIDATE_LINKS: true
