replicaCount: 3

image:
  repository: rinawarp
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: rinawarp.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: rinawarp-tls
      hosts:
        - rinawarp.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "3000"
  - name: LOG_LEVEL
    value: "info"
  - name: POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: rinawarp-postgres
        key: host
  - name: POSTGRES_PORT
    valueFrom:
      secretKeyRef:
        name: rinawarp-postgres
        key: port
  - name: POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: rinawarp-postgres
        key: database
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: rinawarp-postgres
        key: username
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: rinawarp-postgres
        key: password
  - name: REDIS_HOST
    valueFrom:
      secretKeyRef:
        name: rinawarp-redis
        key: host
  - name: REDIS_PORT
    valueFrom:
      secretKeyRef:
        name: rinawarp-redis
        key: port
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: rinawarp-redis
        key: password
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: rinawarp-secrets
        key: jwt-secret
  - name: COOKIE_SECRET
    valueFrom:
      secretKeyRef:
        name: rinawarp-secrets
        key: cookie-secret
  - name: STRIPE_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: rinawarp-stripe
        key: secret-key
  - name: STRIPE_WEBHOOK_SECRET
    valueFrom:
      secretKeyRef:
        name: rinawarp-stripe
        key: webhook-secret
  - name: AI_MODEL_API_KEY
    valueFrom:
      secretKeyRef:
        name: rinawarp-ai
        key: api-key
  - name: AI_MODEL_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: rinawarp-ai
        key: endpoint

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

nodeSelector: {}

tolerations: []

affinity: {}
